# Generated by Django 6.1 on 2026-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('peding', 'معوق')], default='peding', max_length=10),
        ),
    ]
