# Generated by Django 6.1 on 2026-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('pending', 'معوق')], default='pending', max_length=10),
        ),
    ]
